### ISSUE TITLE
Неверный тип поля

### ISSUE THREAD

**Issue by mpankov978** [GulizarHanum/ZooHotel#12]
Если вес будет килограммы + граммы (напр 5.3) - лучше использовать BigDecimal

https://github.com/GulizarHanum/ZooHotel/blob/6e7e610f74cb9c4e415b81408b231087e5d1555f/src/main/java/com/diploma/zoo_hotel/dto/FilterDto.java#L29

**Comment by GulizarHanum** [comment]
Вес разделен по категориям, маленький, средний и т.п., поэтому тип поля верный
